import { readFile, writeFile } from 'node:fs/promises';
import * as cheerio from 'cheerio';

const path = './game/index.html'
const html = await readFile(path);

const $ = cheerio.load(html);

// This assumes you only have one script tag. This is the one that is automatically generated by rpg maker mz
const contents = $('body').find('script');


if (contents.length <= 1) {
// Add more files as needed.
$('body').append('<script type="module" src="js/native/utils.js"></script>');
$('body').append('<script type="module" src="js/native/file.js"></script>');
}
await writeFile(path, $('html').toString())